p=float   (input("Enter the princpal amount :"))
r=float(input("Enter the rate            :"))
t=float(input("Enter the Time            :"))
a =  p * (pow((1 + r / 100) , t))
print("Compound Intrest :",(a-p))
